# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\desktop2\projects\pyqt5\RecursiveSearch\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RecursiveSearch(object):
    def setupUi(self, RecursiveSearch):
        RecursiveSearch.setObjectName("RecursiveSearch")
        RecursiveSearch.resize(684, 791)
        self.centralwidget = QtWidgets.QWidget(RecursiveSearch)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.nothing = QtWidgets.QFrame(self.centralwidget)
        self.nothing.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.nothing.setStyleSheet("QPushButton {\n"
"border: none;\n"
"padding: 5px 10px;\n"
"background-color: #f7f7f7;\n"
"border-radius: 3px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(235, 235, 235);\n"
"}\n"
"\n"
"QFrame {\n"
"border-top-right-radius: 5px;\n"
"border-top-left-radius: 5px;\n"
"    background-color: rgb(83, 83, 83);\n"
"}")
        self.nothing.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.nothing.setFrameShadow(QtWidgets.QFrame.Raised)
        self.nothing.setObjectName("nothing")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.nothing)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dragFrame = QtWidgets.QFrame(self.nothing)
        self.dragFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dragFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dragFrame.setObjectName("dragFrame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.dragFrame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_9 = QtWidgets.QFrame(self.dragFrame)
        self.frame_9.setStyleSheet("image: url(:/images/images/icon.png);\n"
"min-width: 50px;\n"
"max-width: 50px;\n"
"padding: 3px;")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_5.addWidget(self.frame_9)
        self.label_3 = QtWidgets.QLabel(self.dragFrame)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font-weight:bold;\n"
"color: lightgray;\n"
"min-height: 80px;\n"
"max-height: 80px;")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.horizontalLayout_5.setStretch(1, 1)
        self.horizontalLayout.addWidget(self.dragFrame)
        self.horizontalLayout.setStretch(0, 1)
        self.verticalLayout.addWidget(self.nothing)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("border-bottom-right-radius: 5px;\n"
"border-bottom-left-radius: 5px;\n"
"background-color: rgb(102, 102, 102);\n"
"font-size:16px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_2)
        self.stackedWidget.setStyleSheet("color: #fff;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.AutoClicker = QtWidgets.QWidget()
        self.AutoClicker.setObjectName("AutoClicker")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.AutoClicker)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_6 = QtWidgets.QFrame(self.AutoClicker)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_6.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_6.setSpacing(3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_13 = QtWidgets.QFrame(self.frame_6)
        self.frame_13.setStyleSheet("QFrame {\n"
"background-color: #727272;\n"
"color: #fff;\n"
"}")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_23 = QtWidgets.QFrame(self.frame_13)
        self.frame_23.setStyleSheet("QFrame {\n"
"    background-color: rgb(108, 108, 108);\n"
"color: #fff;\n"
"}\n"
"QRadioButton {\n"
"background-color: none;\n"
"}\n"
"")
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.textEdit = QtWidgets.QTextEdit(self.frame_23)
        self.textEdit.setStyleSheet("max-height: 125px;\n"
"min-height: 125px;")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_7.addWidget(self.textEdit)
        self.frame_22 = QtWidgets.QFrame(self.frame_23)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_3 = QtWidgets.QFrame(self.frame_22)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(self.frame_5)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 9)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_select_dir = QtWidgets.QPushButton(self.frame)
        self.btn_select_dir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_select_dir.setStyleSheet("QPushButton {\n"
"background-color: #84c184;\n"
"padding: 5px;\n"
"border-radius: 3px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #66b266;\n"
"}")
        self.btn_select_dir.setObjectName("btn_select_dir")
        self.horizontalLayout_2.addWidget(self.btn_select_dir)
        self.label_directory = QtWidgets.QLabel(self.frame)
        self.label_directory.setAlignment(QtCore.Qt.AlignCenter)
        self.label_directory.setObjectName("label_directory")
        self.horizontalLayout_2.addWidget(self.label_directory)
        self.verticalLayout_4.addWidget(self.frame)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.verticalLayout_8.addWidget(self.frame_3)
        self.frame_34 = QtWidgets.QFrame(self.frame_22)
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_34)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(4)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_8.addWidget(self.frame_34)
        self.verticalLayout_7.addWidget(self.frame_22)
        self.frame_7 = QtWidgets.QFrame(self.frame_23)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.edit_search = QtWidgets.QLineEdit(self.frame_8)
        self.edit_search.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.edit_search.setStyleSheet("\n"
"#edit_search {\n"
"padding: 4px;\n"
"background-color: rgb(132, 132, 132);\n"
"border-radius: 3px;\n"
"border: 1px solid rgb(83, 83, 83);\n"
"}\n"
"\n"
"\n"
"#edit_search:hover {\n"
"padding: 4px;\n"
"    background-color: rgb(140, 140, 140);\n"
"border-radius: 3px;\n"
"border: 1px solid rgb(83,83,83);\n"
"}")
        self.edit_search.setObjectName("edit_search")
        self.horizontalLayout_7.addWidget(self.edit_search)
        self.btn_search = QtWidgets.QPushButton(self.frame_8)
        self.btn_search.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_search.setStyleSheet("QPushButton {\n"
"background-color: #84c184;\n"
"padding: 5px;\n"
"border-radius: 3px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #66b266;\n"
"}")
        self.btn_search.setObjectName("btn_search")
        self.horizontalLayout_7.addWidget(self.btn_search)
        self.verticalLayout_5.addWidget(self.frame_8)
        self.verticalLayout_7.addWidget(self.frame_7)
        self.frame_19 = QtWidgets.QFrame(self.frame_23)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(3)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_40 = QtWidgets.QFrame(self.frame_19)
        self.frame_40.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_40.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_40.setObjectName("frame_40")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_40)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_6 = QtWidgets.QLabel(self.frame_40)
        self.label_6.setStyleSheet("color: lightgray;")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_10.addWidget(self.label_6)
        self.label_last_update = QtWidgets.QLabel(self.frame_40)
        self.label_last_update.setStyleSheet("font-size: 10px;\n"
"color: lightgray;")
        self.label_last_update.setObjectName("label_last_update")
        self.horizontalLayout_10.addWidget(self.label_last_update, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_15.addWidget(self.frame_40)
        self.log = QtWidgets.QListWidget(self.frame_19)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.log.setFont(font)
        self.log.setStyleSheet("background-color: rgb(132, 132, 132);\n"
"border-radius:3px;\n"
"padding:5px;\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"border: 1px solid  rgb(83, 83, 83);")
        self.log.setObjectName("log")
        self.verticalLayout_15.addWidget(self.log)
        self.progressBar = QtWidgets.QProgressBar(self.frame_19)
        self.progressBar.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.progressBar.setStatusTip("")
        self.progressBar.setStyleSheet("QProgressBar{\n"
"font-size: 1px;\n"
"color: rgba(0,0,0,0.1);\n"
"min-height: 4px;\n"
"max-height: 4px;\n"
"\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_15.addWidget(self.progressBar)
        self.verticalLayout_15.setStretch(1, 1)
        self.verticalLayout_7.addWidget(self.frame_19)
        self.verticalLayout_11.addWidget(self.frame_23)
        self.horizontalLayout_6.addWidget(self.frame_13)
        self.verticalLayout_6.addWidget(self.frame_6)
        self.stackedWidget.addWidget(self.AutoClicker)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_current_time = QtWidgets.QLabel(self.frame_4)
        self.label_current_time.setStyleSheet("color: lightgray;\n"
"font-size: 10px;")
        self.label_current_time.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_current_time.setObjectName("label_current_time")
        self.horizontalLayout_3.addWidget(self.label_current_time)
        self.information = QtWidgets.QLabel(self.frame_4)
        self.information.setStyleSheet("color: lightgray;\n"
"font-size: 10px;")
        self.information.setText("")
        self.information.setAlignment(QtCore.Qt.AlignCenter)
        self.information.setObjectName("information")
        self.horizontalLayout_3.addWidget(self.information)
        self.label_mouse_pos = QtWidgets.QLabel(self.frame_4)
        self.label_mouse_pos.setStyleSheet("color: lightgray;\n"
"font-size: 10px;")
        self.label_mouse_pos.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_mouse_pos.setObjectName("label_mouse_pos")
        self.horizontalLayout_3.addWidget(self.label_mouse_pos)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_11 = QtWidgets.QFrame(self.frame_2)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2.addWidget(self.frame_11)
        self.verticalLayout.addWidget(self.frame_2)
        RecursiveSearch.setCentralWidget(self.centralwidget)

        self.retranslateUi(RecursiveSearch)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(RecursiveSearch)

    def retranslateUi(self, RecursiveSearch):
        _translate = QtCore.QCoreApplication.translate
        RecursiveSearch.setWindowTitle(_translate("RecursiveSearch", "RecursiveSearch"))
        self.label_3.setText(_translate("RecursiveSearch", " RecursiveSearch"))
        self.textEdit.setHtml(_translate("RecursiveSearch", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">About </span><span style=\" font-size:16px; font-style:italic;\">Recursive Search </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">Enables you to search any file recursively for a text or phrase within a chosen directory. (e.g. Jesus, Jesus saves)</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">Made With </span><img src=\":/images/images/20x20/cil-heart.png\" /><span style=\" font-size:16px;\"> by Gabe</span></p></body></html>"))
        self.btn_select_dir.setToolTip(_translate("RecursiveSearch", "Start Auto Clicker!"))
        self.btn_select_dir.setText(_translate("RecursiveSearch", "Select Directory"))
        self.label_directory.setText(_translate("RecursiveSearch", "/"))
        self.btn_search.setToolTip(_translate("RecursiveSearch", "Start Auto Clicker!"))
        self.btn_search.setText(_translate("RecursiveSearch", "Search"))
        self.label_6.setText(_translate("RecursiveSearch", "Event Log"))
        self.label_last_update.setText(_translate("RecursiveSearch", "            00:00:00 am"))
        self.label_current_time.setText(_translate("RecursiveSearch", "00:00:00 am"))
        self.label_mouse_pos.setText(_translate("RecursiveSearch", "(x,y)"))
import resources_rc
